<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\IA_Jarvis_Project.Core\IA_Jarvis_Project.Core.csproj" />
    <ProjectReference Include="..\IA_Jarvis_Project.Infrastructure\IA_Jarvis_Project.Infrastructure.csproj" />
    <ProjectReference Include="..\IA_Jarvis_Project.Services\IA_Jarvis_Project.Services.csproj" />
  </ItemGroup>

</Project>
